config/routes.rb
Kittens::Application.routes.draw do
  
  resources :pins

  devise_for :users
  get 'about' => 'pages#about'
  root :to => 'pins#index' 

end

app/models/pin.rb
class Pin < ActiveRecord::Base

	belongs_to :user
	has_attached_file :image#, :styles => { :medium => "320x240>" }

	validates_attachment :image, presence: true,
								 :content_type => { :content_type =>  ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']}

	validates :description, presence: true
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable 
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable      
         
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  #to make our app rely on our custom sanitizer, we need to override the devise_parameter_sanitizer method	
  protected
 
  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end	
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc")
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy
    
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "more me" , "http://somethingnothing.me" %> by <%= link_to "meta me", "https://github.com/mle626/kittens" %>
	</small>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Kittens", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>    
      </ul>
      <ul class="nav navbar-nav pull-right">
      	<% if user_signed_in? %>
        <li><%= link_to "Add +", new_pin_path %></li>
      	<li><%= link_to "Edit Profile", edit_user_registration_path %></li> 
	      	<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li> 
      	<% else %>
	        <li><%= link_to "Login", new_user_session_path %></li>   
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Kittttttensssss</title>
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-info") %>
			<% end %>	
		<%= yield %>
	</div>
	<div id="push"></div>	
		<%= render 'layouts/footer' %>
		
	</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>
	<h3>Hi, <%= current_user.name %>!</h3>
<% else %>	
	<div class="jumbotron">
		<h1>Raaaaaaaaaaaaaaaaar!</h1>
		<p>
			Hi Friends. You found <%= link_to "me", "http://www.geocities.com/spunk1111/pets.htm#cats" %> .
		</p>
		<p>
			<%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-primary btn-lg" %> 	
		</p>	
		<tr>
			<td style="vertical-align: top;"><tt>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				_&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				\`*-.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				)&nbsp;
				_`-.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				.&nbsp; : `.
				.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				: _&nbsp;&nbsp; '&nbsp;
				\&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				; *` _.&nbsp;&nbsp;
				`*-._&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				`-.-'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				`-.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				`&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `.&nbsp;&nbsp;&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				:.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \&nbsp;&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				. \&nbsp; .&nbsp;&nbsp; :&nbsp;&nbsp; .-'&nbsp;&nbsp; .&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				'&nbsp; `+.;&nbsp; ;&nbsp; '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				:&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				:&nbsp; '&nbsp; |&nbsp;&nbsp;&nbsp;
				;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;-. <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				; '&nbsp;&nbsp; : :`-:&nbsp;&nbsp;&nbsp;&nbsp; _.`* ;<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <%= link_to "[bug]", "view-source:http://user.xmission.com/~emailbox/ascii_cats.htm" %> .*' /&nbsp; .*'
				; .*`- +'&nbsp; `*' <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				`*-*&nbsp;&nbsp; `*-*&nbsp;
				`*-*'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
				<br>
			  </tt></td>
			</tr>
		</div>	
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>

<p>
This is a bunch of nonsense that I'm typing as I listen to a tutorial about making a Rails app in one month by a guy who wants everyone to make a page that advertises his site about making a site using Rails in one month.	
</p>
<p>
<%= link_to "This is me trying to make a link using Ruby syntax instead of html tags", "https://github.com/mle626/kittens" %></p>
<p>
<%= link_to "This is a sample application", "https://github.com/mle626/kittens" %>
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<h1>You're logged in!</h1>
<% else %>	
	<div class="jumbotron">
		<h1>Raaaaaaaaaaaaaaaaar!</h1>
		<p>
			Hi Friends. You found <%= link_to "me", "http://www.geocities.com/spunk1111/pets.htm#cats" %> .
		</p>
		<p>
			<%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-primary btn-lg" %> 	
		</p>	
		<tr>
			<td style="vertical-align: top;"><tt>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				_&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				\`*-.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				)&nbsp;
				_`-.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				.&nbsp; : `.
				.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				: _&nbsp;&nbsp; '&nbsp;
				\&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				; *` _.&nbsp;&nbsp;
				`*-._&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				`-.-'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				`-.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				`&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `.&nbsp;&nbsp;&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				:.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \&nbsp;&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				. \&nbsp; .&nbsp;&nbsp; :&nbsp;&nbsp; .-'&nbsp;&nbsp; .&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				'&nbsp; `+.;&nbsp; ;&nbsp; '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				:&nbsp;&nbsp; <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				:&nbsp; '&nbsp; |&nbsp;&nbsp;&nbsp;
				;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;-. <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				; '&nbsp;&nbsp; : :`-:&nbsp;&nbsp;&nbsp;&nbsp; _.`* ;<br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <%= link_to "[bug]", "view-source:http://user.xmission.com/~emailbox/ascii_cats.htm" %> .*' /&nbsp; .*'
				; .*`- +'&nbsp; `*' <br>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				`*-*&nbsp;&nbsp; `*-*&nbsp;
				`*-*'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
				<br>
			  </tt></td>
			</tr>
		</div>	
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
	<%= f.error_notification %>
	<%= f.full_error :image_file_size, class: "alert alert-danger" %>
	<%= f.full_error :image_content_type, class: "alert alert-danger" %>

	<%= f.input :image, label:"Upload an image" %>
	<%= f.input :description, as: :text, input_html: { rows: "3" } %>
 

  <div class="form-actions well well-lg">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image), pin %>
	<p class="description">
		<%= pin.description %>
	</p>
	<p>
		<strong>
			Posted by <%= pin.user.name %>
		</strong>	
	</p>	
	<p>
		<% if current_user == pin.user %>
			<%= link_to 'Edit', edit_pin_path(pin) %>
			<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
	</p>		
		<% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
    <%= render @pins %>
</div>  

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="well">
		  <%= image_tag @pin.image %>	
		<p>
		  <%= @pin.description %>
		</p>
		<p>
		  <%= @pin.user.name %>
		</p>
		<% if current_user == @pin.user %>
		<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<% end %>
		<%= link_to 'Back', pins_path %>
	</div>
	</div>
</div>